[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"
path = "01 - Trebuchet/main.rs"
[[bin]]
name = "day02"
path = "02 - Cube Conundrum/main.rs"

[dependencies]
regex = { version = "1.11.1" }
